import React from 'react';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import { Navbar } from '../components';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={inter.className}>
	
	<Navbar />
	ezra
        {children}
      </body>
    </html>
  );
};

export default RootLayout;

